Repository 2024-Winter-Bootcamp-TeamC/InsideOut-Backend, pull requests merged in 2025-01, with the labels that each got.

#36 [CHORE] 이슈 자동 닫힘
  .github/workflows/close-issue-on-dev.yml
Labels: 🧭 Chore

#40 [FEAT] 보고서 생성 redis 연결 및 7가지 감정 한줄평 프롬프트
  app/crud/ai.py
  app/crud/preparation.py
  app/crud/report.py
  app/models.py
  app/routers/report.py
  app/uploads/10_1.jpeg
  app/uploads/9_1.jpeg
Labels: 🚀 Feat

#46 [FEAT] 7개 감정 ai 한줄평 받아오기 구현
  app/crud/ai.py
  app/crud/emotions.py
  app/crud/preparation.py
  app/main.py
  app/routers/emotions.py
Labels: 🚀 Feat

#52 [FEAT] elevenlabs tts적용
  app/main.py
  app/routers/ai.py
  app/routers/chat.py
  app/test.html
  app/utils/prompt.py
  app/utils/tts.py
  docker-compose.yml
  requirements.txt
Labels: 🚀 Feat, 🏷 Fix

#55 Feat : 보고서 생성과 퍼센테이지 저장 기능 연결
  app/crud/ai.py
  app/crud/report.py
  app/main.py
  app/routers/report.py
  app/schemas/report.py
Labels: 🚀 Feat

#60 fix : 입력 프롬프트 적용 및 레디스 저장 chatroom_id
  app/crud/chat.py
  app/routers/chat.py
Labels: 🏷 Fix

#62 [Test] user 회원가입/ 조회/ 탈퇴/ 로그인 테스트 코드
  app/crud/__init__.py
  app/database.py
  app/routers/__init__.py
  app/schemas/__init__.py
  app/tests/__init__.py
  app/tests/conftest.py
  app/tests/test_api_user.py
  app/tests/test_crud_user.py
  app/tests/test_router_user.py
Labels: 📁 Test

#74 [TEST] chatroom 테스트 코드 작성
  app/crud/user.py
  app/models.py
  app/routers/chatroom.py
  app/tests/test_api_chatroom.py
  app/tests/test_crud_chatroom.py
  app/tests/test_router_chatroom.py
Labels: 📁 Test

#76 [TEST] preparation 테스트 코드 작성
  app/tests/conftest.py
  app/tests/test_api_preparation.py
  app/tests/test_crud_preparation.py
  app/tests/test_router_preparation.py
Labels: 📁 Test

#77 [TEST] emotion 테스트 코드 작성
  app/tests/test_api_emotions.py
  app/tests/test_crud_emotions.py
  app/tests/test_router_emotions.py
Labels: 📁 Test

#79 [TEST] emotionchoose 테스트 코드 작성
  app/tests/test_crud_emotionchoose.py
Labels: 📁 Test

#80 [TEST] report 생성/조회/삭제/목록 조회
  app/routers/report.py
  app/tests/test_api_report.py
  app/tests/test_crud_report.py
  app/tests/test_router_report.py
  requirements.txt
Labels: 📁 Test

#84 [Feat] CI 연동
  .github/workflows/ci.yml
  requirements.txt
Labels: 🚀 Feat

#85 Refactor : 프롬프트 및 당황이->부럽이로 변경
  app/crud/ai.py
  app/crud/chat.py
  app/crud/report.py
  app/database.py
  app/utils/prompt.py
  app/utils/tts.py
Labels: 🧹 Refactor

#91 [Fix] 상황설명만으로 실행 구현
  app/crud/preparation.py
  app/routers/preparation.py
Labels: 🏷 Fix

#93 [Fix] 상황설명만으로 실행 찐구현
  app/crud/preparation.py
Labels: 🏷 Fix
